
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/

//@version=4
strategy("Panneled indicator(s)", overlay=false, pyramiding=1, commission_value=0.2, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

//@version=4
// Inputs
fastLen = input(title="Fast Length", defval=12)
slowLen = input(title="Slow Length", defval=26)
sigLen  = input(title="Signal Length", defval=9)

// MACD calculation
[macdLine, signalLine, _] = macd(close, fastLen, slowLen, sigLen)

// MACD values and line
plot(series=macdLine, color=color.green, linewidth=2)
plot(series=signalLine, color=color.orange, linewidth=2)