
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/

//@version=4
strategy("Panneled indicator(s)", overlay=false, pyramiding=1, commission_value=0.2, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

fastMAlen = input(12, minval=1, title="MACD fast moving average - Indicator")
slowMAlen = input(26, minval=1, title="MACD slow moving average - Indicator")

signalMACDlen = input(9,minval=1, title="MACD signal line moving average - Indicator")



MACD = ema(close, fastMAlen) - ema(close, slowMAlen)
signalMACD = ema(MACD, signalMACDlen)
deltaMACD = MACD - signalMACD

// Plot RSI
plot(deltaMACD)
plot(0)