
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/

//@version=4
strategy("Simple RSI", overlay=false, pyramiding=1, commission_value=0.2, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

// Input
backtestStart = input(defval = timestamp("01 Jan 2020 13:30 +0000"), title = "Backtest Start Time", type = input.time)

rsiOverbought = input(70, minval=1)
rsiOversold = input(30, minval=1)


// RSI calculation
rsiValue = rsi(close, 14)

// Plot RSI
plot(rsiValue, color=color.white, linewidth=2)
plot(rsiOversold, color=color.green)
plot(rsiOverbought, color=color.red)