//@version=4
strategy(title="The ultimate strategy v1", shorttitle="Strategy", overlay=true, pyramiding=1, commission_value=0.2, default_qty_type=strategy.percent_of_equity, default_qty_value=10)

rsiOverbought = input(70, minval=1)
rsiOversold = input(30, minval=1)

stopLossPerc = input(0.7, minval=0.01, step=0.01, title="Stop loss percent")

fastMAlen = input(12, minval=1, title="MACD fast moving average")
slowMAlen = input(26, minval=1, title="MACD slow moving average")

signalMACDlen = input(9,minval=1, title="MACD signal line moving average")

// Trailing stop loss
var entryPrice = float(0)
var stopLossPrice = float(0)


// RSI calculation
rsiValue = rsi(close, 14)

// MACD calculation
MACD = ema(close, fastMAlen) - ema(close, slowMAlen)
signalMACD = ema(MACD, signalMACDlen)
deltaMACD = MACD - signalMACD

fastMA = ema(close,fastMAlen)
slowMA = ema(close,slowMAlen)

// plot SL line
slColor = strategy.position_size > 0 ? color.green : color.black
plot(stopLossPrice, color=slColor)

// Conditions
longPosition = deltaMACD > 0


if strategy.position_size > 0
    stopLossPrice := max(close * stopLossPerc, stopLossPrice)
    if close <= stopLossPrice
        strategy.close("Order", comment="Close")

else if longPosition
    entryPrice := close
    stopLossPrice := close * stopLossPerc
    strategy.entry("Order", strategy.long, comment="Open")